// Community colour palette — mirrors eda/config.py:COMMUNITY_COLORS exactly
// so the live app matches the static network.png generated by the pipeline.
export const COMMUNITY_COLORS: string[] = [
  "#58A6FF", // blue
  "#3FB950", // green
  "#FF7B72", // red
  "#D2A8FF", // purple
  "#FFA657", // orange
  "#39D353", // bright green
  "#F0883E", // amber
  "#79C0FF", // light blue
  "#56D364", // lime
  "#FF9492", // pink
  "#CFF4D2", // mint
  "#B1BAC4", // grey
];

export function communityColor(community: number): string {
  return COMMUNITY_COLORS[community % COMMUNITY_COLORS.length] ?? "#B1BAC4";
}
